services:
    chatterino-proxy:
        image: ghcr.io/mrchuw/chatterino-proxy:latest
        container_name: chatterino-proxy
        # ports:
        #   - ${PORT:-8000}:8000
        volumes:
            - ./config.json:/app/config.json:ro
        restart: unless-stopped
        networks:
            - caddy

networks:
    caddy:
        external: true
