services:
  Alias_site:
    image: ghcr.io/mrchuw/color-in-memory:main
    container_name: color
    # ports:
    #   - ${PORT:-12836}:5454
    environment:
      - ANALYTICS_URL=${ANALYTICS_URL:-}
      - ANALYTICS_UUID=${ANALYTICS_UUID:-}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - caddy

networks:
  caddy:
    external: true