---
services:
  rimgo:
    image: ghcr.io/mrchuw/rimgo:latest
    # ports:
    #   - 33000:3000
    restart: unless-stopped
    user: 65534:65534 # equivalent to `nobody`
    read_only: true
    environment:
      - ADDRESS=${ADDRESS}
      - FIBER_PREFORK=${FIBER_PREFORK}
      - IMGUR_CLIENT_ID=${IMGUR_CLIENT_ID}
      - PORT=${PORT}
      - PRIVACY_CLOUDFLARE=${PRIVACY_CLOUDFLARE}
      - PRIVACY_COUNTRY=${PRIVACY_COUNTRY}
      - PRIVACY_DEVICE=${PRIVACY_DEVICE}
      - PRIVACY_DIAGNOSTICS=${PRIVACY_DIAGNOSTICS}
      - PRIVACY_IP=${PRIVACY_IP}
      - PRIVACY_MESSAGE=${PRIVACY_MESSAGE}
      - PRIVACY_NOT_COLLECTED=${PRIVACY_NOT_COLLECTED}
      - PRIVACY_POLICY${PRIVACY_POLICY}
      - PRIVACY_PROVIDER=${PRIVACY_PROVIDER}
      - PRIVACY_URL=${PRIVACY_URL}
      - SECURE=${SECURE}
      - UMAMI_HOST=${UMAMI_HOST}
      - UMAMI_SCRIPT_URL=${UMAMI_SCRIPT_URL}
      - UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID}
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    # env_file: .env
    networks:
      - caddy

networks:
  caddy:
    external: true