#!/bin/sh

CONFIG_FILE="/etc/ntp.toml"

if [ -f "$CONFIG_FILE" ]; then
    echo "Existing configuration found at $CONFIG_FILE. Skipping auto-generation."
else
    echo "No configuration found. Generating $CONFIG_FILE from environment variables..."

    echo "# Generated by entrypoint script" > $CONFIG_FILE

    if [ -n "$NTP_SERVERS" ]; then
        echo "Using custom NTP servers from environment..."
        SERVERS_LIST="$NTP_SERVERS"
    else
        echo "No NTP_SERVERS defined. Using default providers (Cloudflare, Meta, Google, Pool)..."
        SERVERS_LIST="time.cloudflare.com time.facebook.com time.google.com pool.ntp.org"
    fi

    for server in $SERVERS_LIST; do
        echo "Adding source: $server"
        cat <<EOF >> $CONFIG_FILE
[[source]]
mode = "server"
address = "$server"

EOF
    done
    cat <<EOF >> $CONFIG_FILE
[[server]]
listen = "0.0.0.0:123"
accept-ntp-versions = [3, 4, 5, 6]

[observability]
observation-path = "/run/ntpd-rs.sock"
metrics-exporter-listen = "0.0.0.0:9975"
EOF
fi

rm -f /run/ntpd-rs.sock
ntp-daemon -c $CONFIG_FILE &

while [ ! -S /run/ntpd-rs.sock ]; do
  echo "Waiting for ntpd-rs socket..."
  sleep 1
done

exec ntp-metrics-exporter -c $CONFIG_FILE


